- Dockerfile
Hi,
this patch reduces final image size from 99 MiB to 57 MiB
> concatenate Dockerfile commands - reduces final images size

- docker-compose.yml
With arbitrary server you can also manage non-dockerized or remote databases.
With docker-compose configuration you can more easily manage your phpMyAdmin container.
Fix: image source in docker-compose.yml - use official image from registry instead of local build
> fix for: add support for arbitrary servers and compose configuration file

- config.inc.php
If I set `PMA_PASSWORD=` or `PMA_PASSWORD=''`, this is not working.
Simply not passing this env var solve the issue, with this modification.
> Allow empty password

- README.md
- config.inc.php
This PR allows users to set the user-facing URL (`PmaAbsoluteUri`) to facilitate usage behind reverse proxies.
> Allows to set the user-facing URL, fixes #12

- run.sh
It's a good practice to make the service PID 1
(although php cli does not handle `kill -TERM` at all).
> Make php server PID 1

- Dockerfile
`--no-cache` will avoid cache usage and do an automatic update.
Cache directory deletion is not necessary anymore.
> Improve apk usage

- Dockerfile
To allow exporting databases with many tables (e.g. Prestashop CMS)
> Increase "max_input_vars" value

- .travis.yml
- Dockerfile
- README.md
- docker-compose.testing.yml
- docker-compose.yml
- run.sh
As this is a Docker container running a web application, it would make sense to expose the http port (80) instead of port 8080. A user can always specify the 'external' port to his liking using e.g. `-p 8080:80`.
This PR changes the container itself as well as all references from tests and documentation.
Fixes #18.
> Switch to port 80 (instead of 8080)

- Dockerfile
Added the php-mcrypt module as phpmyadmin 4.0 gives a notice/warning about it.
> Missing php-mcrypt module

- Dockerfile
As per note in previous version of Dockerfile to switch to stable when 3.4 was out; it is.
Also removed comment since it's done.
> Update base image to alpine:latest

- README.md
- config.inc.php
- run.sh
Added a hook to config.inc.php allowing for users to update PHPMYADMIN / config.inc.php settings as can be done in the non-docker version of phpmyadmin.  This allows users to create custom file called "config.userdef.inc.php" which when linked into the container will allow modification of the normal phpmyadmin config settings.
Updated:
config.inc.php - Included the hook at the end of the file.
run.sh - created a blank config.userdef.inc.php file so as to avoid the warnings generated by including a non-existent file in PHP.
README.md - Updated documentation to identify the ability to create the config.userdef.inc.php and how to link it to the container.
> config.userdef.inc.php hook to allow user configured settings.

- config.inc.php
It fix an issue with PMA_VERBOSE and PMA_VERBOSES environment variables when selecting a mysql server.
Thank you
> Adding PMA_VERBOSE and PMA_VERBOSES environment variables

- etc/php.ini
- opcache.save_comments=0 to avoid storing comments which we do not need
- opcache.validate_timestamps=0 the timestamps validation should not be
needed as container is restarted on change
- fixes #71
> Optimize PHP opcache settings

- Dockerfile
Please do not delete /www/sql folder as it contains create_tables.sql file that creates pma tables and phpmyadmin db for configuration storage
> Cancel removal of /www/sql

- Dockerfile
This way we can correctly get error from the mkdir.
Fixes #86
> Split setting variable from export

- Dockerfile
We really do not need documentation source in the Docker image.
Fixes #79
> Cleanup documentation folder

- README.md
You don't need linking to db container in case of arbitrary server
> Remove link to db container

- Dockerfile
- etc/supervisor.d/php.ini
- testing/phpmyadmin_test.py
- testing/test-docker.sh
This switches the base to the upstream PHP FPM Alpine Docker image, so we can benefit from the maintenance there.
I included and configured the same php extensions as before.
This might be a dependency task of #56.
> Use upstream PHP FPM Alpine Docker image

- Dockerfile
Note: `RUN chmod u+rwx /run.sh` is not necessary, the `RUN mkdir` block has been merged into the other one.
> Enhance caching by moving trivial tasks to the end

- Dockerfile
- etc/nginx.conf
- etc/php-fpm.conf
- run.sh
`nobody` seems not to be a valid group, so using `nogroup` instead.
This should be carefully tested, I didn't run into any issue myself.
> Use "nogroup" as group name

- Dockerfile
- run.sh
Because of the condition it's impossible to run anything else than `phpmyadmin`. The `exec "$@"` in `run.sh` fixes this.
`loglevel=info` is already the [default](http://supervisord.org/logging.html#activity-log).
> Run supervisord in CMD

- README.md
for ones that prefer not to have unexpected version update (but patches are ok), prefer `X.Y` docker tag over `latest`.
improve wording as technically there is no 4.8 branch yet
> readme: 4.8 tag is also present

- Dockerfile-alpine.template
- Dockerfile-debian.template
- update.sh
From https://github.com/phpmyadmin/docker/pull/200#issuecomment-477903111
> I wonder if there's a way to update the version information in one place instead of needing to update four files on each new release.
Here we go.
cc @ibennetch
> Fetch latest version from api

- README.md
- generate-stackbrew-library.sh
This script outputs the format used by the [docker library](https://github.com/docker-library/official-images/tree/master/library).
<details>
<summary>Example output</summary>
```
Maintainers: Isaac Bennetch <bennetch@gmail.com>
Michal Čiha <michal@cihar.com>
GitRepo: https://github.com/phpmyadmin/docker.git
Tags: 4.8.5-apache, 4.8-apache, 4-apache, 4.8.5, 4.8, 4
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le
GitCommit: 78e3cb7aba41b233281f81d8b264d95505c43c96
Directory: apache
Tags: 4.8.5-fpm, 4.8-fpm, 4-fpm
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le
GitCommit: 78e3cb7aba41b233281f81d8b264d95505c43c96
Directory: fpm
Tags: 4.8.5-fpm-alpine, 4.8-fpm-alpine, 4-fpm-alpine
Architectures: amd64, arm32v7, arm64v8, i386, ppc64le
GitCommit: …
```
> Add generate-stackbrew-library.sh

- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
https://github.com/docker-library/wordpress/issues/407
Before a68a25c673c8a0ca55589e81dd4540c2c31e9e97 this was in a inconsistent state.
> Drop opcache from cli actions

- README.md
- apache/docker-entrypoint.sh
- docker-entrypoint.sh
- fpm-alpine/docker-entrypoint.sh
- fpm/docker-entrypoint.sh
Simple PR to hide the PHP version by adding `expose_php = Off` to `php.ini` for security reasons. When working behind a reverse proxy it is possible to ignore the header, but disabling it for everyone might be still the better choice. Change tested and working.
> Hide PHP version

- .gitattributes
- Dockerfile-alpine.template
- Dockerfile-debian.template
- README.md
- apache/Dockerfile
- apache/docker-entrypoint.sh
- docker-entrypoint.sh
- fpm-alpine/Dockerfile
- fpm-alpine/docker-entrypoint.sh
- fpm/Dockerfile
- fpm/docker-entrypoint.sh
Ref: #238
Closes: #240
Closes: #239
Closes: #233
Closes: #189
Closes: #139
Duplicate of: #241 that was reverted after a merge mistake
> Some improvements and implementations

- .travis.yml
- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
- hooks/build
Related to https://github.com/phpmyadmin/docker/pull/274 and https://github.com/docker-library/official-images/pull/7288
Spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md
> Add org.opencontainers.image.* labels

- fpm-alpine/Dockerfile
Added tzdata package so that the TZ env variable is handled correctly.
```bash
docker run --rm -it -e "TZ=Europe/Luxembourg" 5c96a8fcaca0 date
Fri Mar 27 23:15:48 CET 2020
docker run --rm -it -e "TZ=Europe/London" 5c96a8fcaca0 date
Fri Mar 27 22:15:56 GMT 2020
```
Fixes #281
> #281 Added tzdata package

- README.md
Default value format "2048Kb" will not work with Apache !
> Specify UPLOAD_LIMIT format

- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
default `max_input_vars` value is 1000, and it's often too low for DB with large number of tables export, causing fatal error:
> Fatal error: Uncaught TypeError: Argument 5 passed to PhpMyAdmin\Export::getFilenameAndMimetype() must be of the type string, null given, called in /var/www/html/export.php on line 380 
this PR:
- raises the value of it to 10000
- exposes it in the INI file, so it's easier to edit if anyone desire so
> add 'max_input_vars = 10000' to phpmyadmin_misc.ini

- .github/workflows/ci.yml
- README.md
Once the tests have been [moved upstream](https://github.com/docker-library/official-images/tree/master/test/tests) we can finally remove Travis.
> Add GitHub CI

- README.md
- apache/config.inc.php
- apache/docker-entrypoint.sh
- config.inc.php
- docker-entrypoint.sh
- fpm-alpine/config.inc.php
- fpm-alpine/docker-entrypoint.sh
- fpm/config.inc.php
- fpm/docker-entrypoint.sh
Make it possible to change the upload_limit without being able to easily change the maximum execution time for php and phpmyadmin, I often ran into problems changing the configs in the docker container.
I can imagine that other users have the same problem, especially with big sql files, slow machines or remote servers and a limited bandwidth.
> Add the possibility to change max_execution_time

- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
`sks-keyservers.net` was shut down some time ago, see https://sks-keyservers.net/ (expired cert). `keys.gnupg.net` is just an alias. `pgp.mit.edu` isn't part of the `sks-keyservers.net` pool, but also runs SKS and will likely suffer the same fate (like any other SKS keyserver). It is currently unavailable, but there was no take-down notice (yet). The same is true for `keys.openpgp.org`. I didn't remove those because we should assume that they are unavailable just temporarily. Use `keys.openpgp.org` as main alternative.
> Fix GPG keyservers

- README.md
- apache/docker-entrypoint.sh
- docker-entrypoint.sh
To deal with both #340 and #187, this PR allows for a new Environment variable `APACHE_PORT` to change the default port from `80` to something user defined. If unset, it remains using port 80
Fixes: #340
> Allow a different Apache port with APACHE_PORT 

- docker-entrypoint.sh
Setting port to 8000-8099 caused issues after a restart.
Ex: Port got set from 8090 to 809090 resulting in error AH00526.
Using full line replace as ports.conf next character is new line.
> Fix issue port 80- range when using APACHE_PORT

- README.md
- config.inc.php
When hosting this image on an Azure hosted container instance, I can mount an Azure FileShare to a local path for uploads but I can't add custom file to the local volume to set the configuration.
This PR adds support setting the UploadDir and SaveDir through environment variables.
> Add ENV PMA_UPLOADDIR and PMA_SAVEDIR ENVs

- CHANGELOG.md
- Dockerfile-alpine.template
- Dockerfile-debian.template
- README.md
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
this allows date pickers in UI to pick up the right time
Fixes: #133
> Fix #133 - Add `TZ` env var to change PHP `date.timezone`

- CHANGELOG.md
- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
PHP 8.2 has been generally available on 2022-12-08 and has had quite a few patch releases. It can be expected to be pretty stable. Active support for PHP 8.1 is ending 2023-11-25.
I have run the end-to-end tests with `make run-tests`, all have passed.
Previous upgrade to PHP 8.1: d1f327e4627ed01454438844a2c96f075bf2f1e8
> Update to PHP 8.2

- Dockerfile-alpine.template
- Dockerfile-debian.template
- README.md
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
- testing/phpmyadmin_test.py
Ref: #274 (who removed it completely)
Ref: #198
Ref: https://github.com/phpmyadmin/docker/issues/398#issuecomment-1462836479
> Add back a /sessions volume for sessions persistence

- README.md
- config.inc.php
> Support adding custom configurations in `/etc/phpmyadmin/conf.d`

- CHANGELOG.md
- Dockerfile-debian.template
- apache/Dockerfile
- fpm/Dockerfile
This also adds a test that makes sure all extension libraries are installed (buld fails if `ldd` outputs a line with ` => not found`)
Note: the extdir variable is needed because if we execute php after the libraries are removed it will print warnings causing the ldd command to fail
Fixes: #416
> Fix for debian 12 issue (#416) that caused libraries for extensions to be uninstalled

- Dockerfile-alpine.template
- Dockerfile-debian.template
`GMP` or `bcmath` is required when second factor authentication is enabled.
> add extension bcmath for 2nd factor authentication

- Dockerfile-debian.template
- apache/Dockerfile
- fpm/Dockerfile
This applies the fixes suggested in https://github.com/docker-library/official-images/pull/14960
Ref: #416
Ref: #417
> Better fix for #416

- README.md
- apache/config.inc.php
- apache/docker-entrypoint.sh
- config.inc.php
- docker-entrypoint.sh
- fpm-alpine/config.inc.php
- fpm-alpine/docker-entrypoint.sh
- fpm/config.inc.php
- fpm/docker-entrypoint.sh
enable ssl connection with upstream. no ca used. 
variable introduced: 
`PMA_SSL` for single upstream
`PMA_SSLS` for multiple upstream
`docker run ... -e PMA_HOSTS="mysql-notls,mysql-tls" -e PMA_SSLS="0,1" ...`
> Enable SSL for all server

- docker-entrypoint.sh
For Docker in rootless-mode having the default umask of Docker set to 0007, the file will get created readable only to root.
Changed the ownership of that file to be readable by www-data.
Adresses #187
See details in Comment https://github.com/phpmyadmin/docker/issues/187#issuecomment-1872177089
> Fix Permissions of config.secret.inc.php

- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
I have tested the new Dockerfiles and builded multiples images to test the mTLS options,here multiples screens.
I have defined 2 PMA hosts: one without cert and mtls, and the other one with correct configuration. This way I have tested cross configuration files for cross databases auth system (so we can use SSL, mTLS and plain text in the same container).
Firstly, the incorrect configuration:
We can see that MaxScale, configured with mTLS is denying the first auth request. No new feature here.
Now with the correct configruation:
No error on MaxScale size, certs are accepted by MariaDB and PMA is connected and we get SSL/MariaDB server informations. The new feature is working.
But during tests, I seen that the **helpers.php** was missing in templates and in generated Dockerfiles. So it was …
> Fix Dockerfile templates: add helpers.php

- Dockerfile-alpine.template
- Dockerfile-debian.template
- apache/Dockerfile
- fpm-alpine/Dockerfile
- fpm/Dockerfile
Sometimes the old way generates warnings when building
> Update ENV statements to use = to match Docker standards
