Dockerfile

Signed-off-by: ZhiFeng Hu <hufeng1987@gmail.com>

Increase PHP file upload size limit to 64MB

---

README.md
config.inc.php
run.sh

User configurattion

---

Dockerfile

This way we can reproduce build of tags, with latest approach used so
far, you would always get the latest version even when building older
tag.

Specify version in variable

---

.travis.yml
Dockerfile
docker-compose.yml
etc/nginx.conf
etc/php-fpm.conf
etc/php.ini
etc/supervisor.d/nginx.ini
etc/supervisor.d/php.ini
run.sh
test-docker.sh

Replaced php built in server with supervisord + nginx + php-fpm.
This is still work in progress.

Use supervisor +  nginx + php-fpm

---

etc/nginx.conf
etc/php-fpm.conf
etc/supervisor.d/php.ini
run.sh
test-docker.sh

Start PHP-FPM as nobody

---

etc/nginx.conf
etc/php-fpm.conf
run.sh
test-docker.sh

Avoid encoding PHP version in socket or log name

---

.dockerignore
.travis.yml
README.md
config.inc.php
config.test.inc.php
run.sh

Fix user configuration and add tests for it

---

etc/nginx.conf

Fixes several reported issues.

Improve nginx setup

---

.travis.yml
Dockerfile
README.md
etc/php.ini
etc/phpmyadmin/config.inc.php

Try to reorder commands for better Docker layer caching

---

Dockerfile
etc/supervisor.d/php.ini

Also switch to PHP 7
Fixes #34

Upgrade to Alpine 3.5

---

.travis.yml

Run Travis tests on Trusty

---

README.md

Thank you for your excellent product always.
This description would be helpful for new users.
`PMA_PORTS` has been working on my container.

Added description of `PMA_PORTS`

---

Dockerfile

Update to Alpine 3.7

---

etc/phpmyadmin/config.inc.php

See https://github.com/phpmyadmin/docker/issues/151

Possiblity to configure the phpMyAdmin configuration storage

---

etc/phpmyadmin/config.inc.php

Move back compress and AllowNoPassword to default configuration

---

Dockerfile

@nijel this fixes a bug in #167

Fix filename in rm command

---

Dockerfile

See https://bugs.debian.org/913614

Update "gpg" invocations to use "--batch"

---

.dockerignore

Remove .dockerignore

---

README.md

https://github.com/phpmyadmin/docker/issues/108#issuecomment-519323193

Add documentation for using secrets.

---

.travis.yml
apache/Dockerfile
fpm-alpine/Dockerfile
fpm/Dockerfile

Ref: #238
Closes: #240
Closes: #239
Closes: #233
Closes: #189

Increase limits for upload and post

---

.gitignore
.travis.yml
Makefile
README.md
docker-compose.testing.yml
docker-entrypoint.sh
testing/Dockerfile
testing/conftest.py
testing/phpmyadmin_test.py
testing/test-docker.sh

Documentation said there is support for, but there was no code to implement this

Added support for PMA_PASSWORD_FILE

---

README.md

Standardize this list and adjust Docker Hub to match.
Closes #256, closes #231, closes #229, closes #214
Signed-off-by: Isaac Bennetch <bennetch@gmail.com>

Improve documentation of which Docker tags we offer;

---

Dockerfile-alpine.template
Dockerfile-debian.template
apache/Dockerfile
apache/docker-entrypoint.sh
docker-entrypoint.sh
fpm-alpine/Dockerfile
fpm-alpine/docker-entrypoint.sh
fpm/Dockerfile
fpm/docker-entrypoint.sh

Applied some feedback from https://github.com/docker-library/official-images/pull/7288

Apply various minor enhancements

---

Dockerfile-alpine.template

Added the tzdata package also the the Dockerfile-alpine.template file...

#281 Added tzdata also to the template alpine file

---

Dockerfile-alpine.template
Dockerfile-debian.template
docker-entrypoint.sh

Fixes #277
Signed-off-by: Isaac Bennetch <bennetch@gmail.com>

Extract downloaded files directly to web root /var/www/html/

---

.travis.yml
Dockerfile-alpine.template
Dockerfile-debian.template
apache/Dockerfile
apache/docker-entrypoint.sh
docker-entrypoint.sh
fpm-alpine/Dockerfile
fpm-alpine/docker-entrypoint.sh
fpm/Dockerfile
fpm/docker-entrypoint.sh
hooks/build

Cleanup according to review

---

Dockerfile-alpine.template
Dockerfile-debian.template
apache/Dockerfile
fpm-alpine/Dockerfile
fpm/Dockerfile
update.sh

Fixes https://github.com/docker-library/official-images/pull/7288#issuecomment-625555257

Add SHA checksum

---

README.md

Fix Docker hub tags page link in README

Fix docker hub tags page link

---

README.md
apache/docker-entrypoint.sh
docker-entrypoint.sh
fpm-alpine/docker-entrypoint.sh
fpm/docker-entrypoint.sh
testing/phpmyadmin_test.py

Add PMA_CONTROLPASS to variables thas can be read from a file using

Add PMA_CONTROLPASS 

---

Dockerfile-alpine.template
Dockerfile-debian.template
README.md
apache/Dockerfile
apache/docker-entrypoint.sh
docker-entrypoint.sh
fpm-alpine/Dockerfile
fpm-alpine/docker-entrypoint.sh
fpm/Dockerfile
fpm/docker-entrypoint.sh
testing/phpmyadmin_test.py

https://github.com/docker-library/official-images/pull/9426#issuecomment-760553422

Generate phpmyadmin-misc.ini from ENVs

---

Dockerfile-alpine.template
Dockerfile-debian.template
apache/Dockerfile
apache/docker-entrypoint.sh
docker-entrypoint.sh
fpm-alpine/Dockerfile
fpm-alpine/docker-entrypoint.sh
fpm/Dockerfile
fpm/docker-entrypoint.sh

https://github.com/docker-library/official-images/pull/9426#issuecomment-771834823

Add expose_php env back
